### ISSUE TITLE
SPC play issue

### ISSUE THREAD

**Issue by VargSilvermane** [emukidid/SNES_APU_SD#4]
When playing a track the first note is played, hangs on the note and fades after a second. No further notes are played.

Hardware used: 
Mega Shield with integrated APU
Arduino Mega 2560 r3 

Software:
Arduino IDE 1.8.13
SDFAT by Bill Greiman
RTClib by Adafruit

**Comment by emukidid** [comment]
Try messing with the PRESCALER value in the .ino, some mega clones have issues with the default speed.

**Comment by VargSilvermane** [comment]
No luck, I tried a prescaler of 1 and 2. I should also mention the arduino _should_ be a genuine unit, barring an counterfeit chip on arduinos product, seeing as I purchased it from them.

**Comment by Oj5000** [comment]
Any luck getting this working? Could be to do with the changes made in v3 of the hardware

**Comment by VargSilvermane** [comment]
Yes, though it was a while ago. Trying to remember, I believe it had to do with the SDFAT library and compatibility with various capacity SD cards. I ended up swapping out the library with another version and managed to get it working well. Incidentally I remade the hardware into a more portable format since the original post. (handheld case with upgraded screen and battery/charger)
